# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  database: microtwittter_development
  username: microtwitter_user
  password: ENV["DATABASE_PASSWORD"]
  pool: 5

development:
  <<: *default
  database: microtwittter_development
  username: microtwitter_user
  password: ENV["DATABASE_PASSWORD"]

test:
  <<: *default
  database: microtwittter_test
  username: microtwitter_user
  password: ENV["DATABASE_PASSWORD"]

production:
  <<: *default
  database: microtwittter_production
  username: microtwitter_user
  username: microtwitter
  password: ENV["DATABASE_PASSWORD"]
 
