# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4a214b17ae35e69911b8c6fab9e5aef20b0090a4878f8d70e6c1d962148d25e0b40dc005e1afaa77862369d23f97a56b20d34f784b7c7d93386cb64952e7aba

test:
  secret_key_base: 309358dea219843f6143108f8f6cc54fbb3b962d31a40321d0d5ac303ba5f7f0997c3e6ab6ff79f515fbfc5439b72e396e7096901c5d16a5cdbd5fc314bd2cea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
